l_polish:
 MESSAGE_SETTINGS_WINDOW_NAME: "Ustawienia wiadomości"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Kliknij, aby otworzyć ustawienia wiadomości#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nZmień częstotliwość i widoczność wiadomości według filtrowanych grup."
 MESSAGE_SETTINGS_WINDOW_RESET: "Przywróć domyślne"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Zresetuj ustawienia wiadomości#!\n#I Kliknij, aby zresetować bieżące zmiany i przywrócić ustawienia domyślne#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Zastosuj zmiany"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Kliknij, aby zamknąć ustawienia wiadomości i zapisać bieżące zmiany#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Tablica aktualności"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Powiadomienie typu toast"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Wyskakujące okienko"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Nigdy"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Grupa filtrów"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Nazwa grupy filtrów wiadomości"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Wygląd"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Wybierz sposób wyświetlania wiadomości z tej grupy filtrów"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pauza"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Zdecyduj, czy gra powinna zostać zatrzymana, kiedy pojawią się wiadomości z tego filtra"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Włącz pauzę automatyczną#!\n#I Włącz, aby zatrzymać grę, kiedy pojawią się wiadomości z tego filtra#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Odrzuć wiadomość#!\n#I Kliknij, aby odrzucić bieżącą wiadomość i wyświetlić następną wiadomość w kolejce#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Niestandardowa wiadomość"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Niestandardowa wiadomość#!\n#I Kliknij, aby napisać niestandardową wiadomość do siebie i wybrać czas jej otrzymania#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Czas nadejścia: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Tytuł:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Opis:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Odrzuć"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Odrzuć wiadomość#!\n#I Kliknij, aby odrzucić bieżącą wiadomość#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Wyślij"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Wyślij#!\n#I Kliknij, aby wysłać bieżącą wiadomość#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Dzień"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Miesiąc"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Rok"
